"""Stage 8: export Giva (asset id lyra) to Unity: Lyra.fbx + Lyra.manifest.json + Textures/.

  blender -b out/giva_face.blend --python s8_export.py [-- --dry]

* built-in hair meshes (Hair_*: the designer presets still use them) are carried over from the committed
  Lyra.fbx and re-bound to the new head through their bind poses (head within 1 cm of the old one)
* mesh / material names follow the contract (STYLE.md); max 4 influences; empty shape keys dropped
* manifest: the existing schema + "correctives" (CorrectiveShapes.cs convention), materialDefs for every slot
"""
import bpy, sys, os, json, math, importlib, shutil, subprocess
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:0] = [os.path.join(HERE, "lib"), HERE]
import numpy as np
from mathutils import Matrix
import gv, mpfb_build
for m in (gv, mpfb_build):
    importlib.reload(m)
P = gv.P
A = gv.args()
rig = bpy.data.objects[gv.RIG]
TEX = os.path.join(gv.OUT, "tex")
DST = gv.LYRA_DIR
DST_TEX = os.path.join(DST, "Textures")
SCRATCH = os.path.join(gv.OUT, "export_tmp")
os.makedirs(SCRATCH, exist_ok=True)

KIND = {"Body": "body", "Eyes": "eyes", "Brows": "brows", "Lashes": "lashes", "Teeth": "teeth", "Tongue": "tongue",
        "Top": "garment", "Pants": "garment", "Gloves": "gloves", "Boots": "boots", "Harness": "gear", "HipModule": "armor",
        "ThighRig": "gear", "Visor": "gear", "ShoulderR": "armor", "ForearmGuardL": "armor"}


def committed_fbx():
    p = os.path.join(SCRATCH, "Lyra_committed.fbx")
    if not os.path.exists(p):
        data = subprocess.run(["git", "-C", gv.ROOT, "show", "HEAD:unity/EchoesOfAether/Assets/Art/Characters/Lyra/Lyra.fbx"],
                              capture_output=True).stdout
        open(p, "wb").write(data)
    return p


def carry_old_hair():
    before = set(bpy.data.objects)
    bpy.ops.import_scene.fbx(filepath=committed_fbx(), automatic_bone_orientation=False)
    new = [o for o in bpy.data.objects if o not in before]
    arm = next(o for o in new if o.type == "ARMATURE")
    styles = []
    for o in new:
        if o.type != "MESH" or not o.name.startswith("Hair_"):
            continue
        if o.name.split(".")[0] == "Hair_waves" or bpy.data.objects.get(o.name.split(".")[0]) not in (None, o):
            continue                     # generated by s7c (current scene), never carried from the committed FBX
        mw = o.matrix_world.copy()
        me = o.data
        # bind-pose remap: v' = sum_b w_b Rest_new_b Rest_old_b^-1 v (all shape keys too)
        mats = {}
        for g in o.vertex_groups:
            bo, bn = arm.data.bones.get(g.name), rig.data.bones.get(g.name)
            if bo is None or bn is None:
                continue
            mats[g.index] = np.array((rig.matrix_world @ bn.matrix_local) @ (arm.matrix_world @ bo.matrix_local).inverted())
        W = np.zeros((len(me.vertices), 4, 4))
        ws = np.zeros(len(me.vertices))
        for v in me.vertices:
            for e in v.groups:
                M = mats.get(e.group)
                if M is not None and e.weight > 0:
                    W[v.index] += M * e.weight
                    ws[v.index] += e.weight
        ok = ws > 0
        W[ok] /= ws[ok, None, None]
        W[~ok] = np.eye(4)

        def remap(co):
            X = np.concatenate([(np.array(mw) @ np.concatenate([co, np.ones((len(co), 1))], 1).T).T[:, :3], np.ones((len(co), 1))], 1)
            return np.einsum("nij,nj->ni", W, X)[:, :3]
        keys = me.shape_keys.key_blocks if me.shape_keys else []
        if keys:
            for k in keys:
                a = np.empty(len(me.vertices) * 3, np.float32)
                k.data.foreach_get("co", a)
                k.data.foreach_set("co", remap(a.reshape(-1, 3).astype(np.float64)).astype(np.float32).ravel())
        co = gv.get_co(o)
        gv.set_co(o, remap(co))
        o.parent = None
        o.matrix_world = Matrix.Identity(4)
        for md in list(o.modifiers):
            o.modifiers.remove(md)
        gv.link_armature(o, rig)
        styles.append(o.name[5:])
    for o in new:
        if o.type != "MESH" or not o.name.startswith("Hair_") or o.name.split(".")[0][5:] not in styles:
            gv.remove(o)
    gv.log("carried hair styles", styles)
    return sorted(styles)


def clean(o):
    me = o.data
    # drop empty shape keys
    if me.shape_keys:
        X = gv.basis_co(o)
        for k in list(me.shape_keys.key_blocks[1:]):
            a = np.empty(len(me.vertices) * 3, np.float32)
            k.data.foreach_get("co", a)
            if np.abs(a.reshape(-1, 3) - X).max() < 2e-5:
                o.shape_key_remove(k)
        if len(me.shape_keys.key_blocks) == 1:
            o.shape_key_clear()
    names, W = gv.bone_weights(o)
    if names:
        gv.write_weights(o, names, gv.limit_normalize(W, 4, 0.01))
    for g in list(o.vertex_groups):
        if not g.name.startswith(P):
            o.vertex_groups.remove(g)
    for an in [a.name for a in me.attributes if not a.name.startswith((".", "position", "UVMap", "Strand", "sharp", "material_index"))]:
        if an in me.attributes and an not in ("UVMap",):
            try:
                me.attributes.remove(me.attributes[an])
            except Exception:
                pass
    for lay in [u.name for u in me.uv_layers if u.name != me.uv_layers.active.name and u.name != "Strand"]:
        me.uv_layers.remove(me.uv_layers[lay])


def copy_mpfb_tex():
    out = {}
    pairs = {"Teeth": ("teeth", "teeth_base"), "Tongue": ("tongue", "tongue01")}
    for mat, (sub, asset) in pairs.items():
        d = os.path.join(gv.MPFB_DATA, sub, asset)
        if not os.path.isdir(d):
            continue
        pngs = sorted(f for f in os.listdir(d) if f.lower().endswith(".png") and "normal" not in f.lower() and "spec" not in f.lower())
        if not pngs:
            continue
        dst = f"{mat}_{pngs[0]}"
        shutil.copyfile(os.path.join(d, pngs[0]), os.path.join(TEX, dst))
        out[mat] = [dst]
    return out


def main():
    styles = carry_old_hair()
    if bpy.data.objects.get("Hair_waves"):
        styles = sorted(set(styles) | {"waves"})
    for o in [o for o in bpy.data.objects if o.name.endswith("_high")]:
        gv.remove(o)
    for c in list(bpy.data.collections):
        if c.name == "HIGH":
            bpy.data.collections.remove(c)
    meshes = [o for o in bpy.data.objects if o.type == "MESH" and o.parent is rig]
    for o in [o for o in bpy.data.objects if o.type == "MESH" and o.parent is not rig]:
        gv.remove(o)
    for o in meshes:
        clean(o)
    atl = json.load(open(os.path.join(TEX, "atlases.json")))
    textures = {}
    textures["Garment_Top"] = [atl["Garment_Top"]["mask"], atl["Garment_Top"]["normal"]]
    textures["Garment_Pants"] = [atl["Garment_Pants"]["mask"], atl["Garment_Pants"]["normal"]]
    for k in ("Armor", "Boots", "Gloves", "Cloth_Gear"):
        if k in atl:
            textures[k] = atl[k]
    sk = atl["Skin"]
    textures["Skin"] = [sk["skins"]["medium"], sk["normal"], sk["maskMap"]]
    textures["Eyes"] = ["Eye_grey.png"]
    textures["Brows"] = atl["Brows"]
    textures["Lashes"] = atl["Lashes"]
    textures.update(copy_mpfb_tex())
    for st in styles:
        textures["Hair_" + st] = [f"Hair_{st}_Color.png"]
    # correctives that exist on some exported mesh
    cdefs = json.load(open(os.path.join(gv.OUT, "correctives.json")))
    present = set()
    for o in meshes:
        if o.data.shape_keys:
            present |= {k.name for k in o.data.shape_keys.key_blocks[1:]}
    corr = [{k: d[k] for k in ("shape", "bone", "parent", "child", "axis", "from", "to")} for d in cdefs if d["shape"] in present]
    man_meshes = []
    for o in sorted(meshes, key=lambda x: x.name):
        me = o.data
        me.calc_loop_triangles()
        kind = KIND.get(o.name, "hair" if o.name.startswith("Hair_") else "gear")
        shapes = [k.name for k in me.shape_keys.key_blocks[1:]] if me.shape_keys else []
        man_meshes.append({"name": o.name, "kind": kind, "materials": [m.name for m in me.materials],
                           "verts": len(me.vertices), "tris": len(me.loop_triangles), "shapes": shapes})
    visible = [m for m in man_meshes if not (m["kind"] == "hair" and m["name"] != "Hair_waves")]
    body = bpy.data.objects["Body"]
    height = round(float(gv.basis_co(body)[:, 2].max()), 3)
    pal = {"outfit": "#55575e", "accent": "#5e2bb8", "armor": "#a8a4b4", "glow": "#ff2bd6", "glow2": "#9b5cff",
           "skin": "#c79878", "hair": "#5a3826", "eyes": "#7a5a32"}
    mdefs = {
        "Garment_Top": {"type": "garment", "mask": textures["Garment_Top"][0], "normal": textures["Garment_Top"][1],
                        "tint": "outfit/accent (runtime composite): R accent panels, G trim/zip, A seam+AO darkening"},
        "Garment_Pants": {"type": "garment", "mask": textures["Garment_Pants"][0], "normal": textures["Garment_Pants"][1],
                          "tint": "outfit*0.88/accent (runtime composite)"},
        "Skin": {"type": "skin", "normal": sk["normal"], "maskMap": sk["maskMap"]},
        "Metal": {"type": "lit", "color": "#a7adb5", "metallic": 1.0, "smoothness": 0.68},
        "Glow": {"type": "emissive", "tint": "glow"}, "Glow2": {"type": "emissive", "tint": "glow2"},
        "Screen": {"type": "emissive", "tint": "glow*0.6"},
    }
    for k, tint in (("Armor", "armor"), ("Boots", None), ("Gloves", "outfit*0.75"), ("Cloth_Gear", None)):
        if k in textures:
            mdefs[k] = {"type": "lit", "baseMap": textures[k][0], "normal": textures[k][1], "maskMap": textures[k][2],
                        "maskMapLayout": "R metallic, G occlusion, B paint mask, A smoothness", "tint": tint}
    for st in styles:
        mdefs["Hair_" + st] = {"type": "hair", "baseMap": f"Hair_{st}_Color.png", "alphaClip": 0.35 if st in ("wavy", "waves") else 0.4, "tint": "hair"}
        if st == "waves":
            mdefs["Hair_" + st]["strandData"] = True      # UV2: x root->tip, y depth in the hair mass (EOA/Hair)
    manifest = {
        "character": "lyra", "name": "Lyra", "gender": "female", "height": height, "fbx": "Lyra.fbx",
        "meshes": man_meshes, "textures": textures, "defaultHair": "waves" if "waves" in styles else "wavy", "hairStyles": styles, "facialHair": [],
        "morphs": sorted({s for m in man_meshes for s in m["shapes"] if s.startswith("m_")}),
        "expressions": sorted({s for m in man_meshes for s in m["shapes"] if s.startswith("x_")}),
        "visibleTris": sum(m["tris"] for m in visible),
        "pipeline": "giva-v2-2026-10 (blender/heroes_v2/giva)",
        "skins": sk["skins"],
        "skinMaps": {"normal": sk["normal"], "maskMap": sk["maskMap"], "stubble": None},
        "eyeLayout": {"note": "iris centred at uv (0.5, 0.5); ellipse d = sqrt(4*du^2 + dv^2) < 0.085 (matches CharacterModel.ApplyEyes)",
                      "variants": ["Eye_grey.png"]},
        "palette": pal,
        "hairAlphaCutoff": {"default": 0.4, "wavy": 0.35, "waves": 0.35, "curly": 0.4, "bun": 0.38, "frenchbraid": 0.38, "Brows": 0.4, "Lashes": 0.3},
        "hairDye": {"wavy": "Hair_wavy_Dye.png"} if os.path.exists(os.path.join(DST_TEX, "Hair_wavy_Dye.png")) else {},
        "optionalParts": {},
        "materialDefs": mdefs,
        # EOA/Skin: Giva's own fine pore tile and a warm, slightly softer scatter (young skin)
        "skinShading": {"poreMap": "Giva_Pores_Normal.png", "poreTiling": 24, "poreStrength": 0.5,
                        "sssTint": [0.95, 0.38, 0.3], "sssStrength": 0.72, "sssWrap": 0.58},
        "correctives": corr,
    }
    if "--dry" in A:
        print(json.dumps({k: v for k, v in manifest.items() if k not in ("meshes",)}, indent=1)[:3000])
        return
    # FBX
    bpy.ops.object.select_all(action="DESELECT")
    rig.select_set(True)
    for o in meshes:
        o.select_set(True)
    bpy.context.view_layer.objects.active = rig
    os.makedirs(DST_TEX, exist_ok=True)
    fbx = os.path.join(DST, "Lyra.fbx")
    bpy.ops.export_scene.fbx(
        filepath=fbx, use_selection=True, object_types={"ARMATURE", "MESH"}, apply_scale_options="FBX_SCALE_ALL",
        axis_forward="-Z", axis_up="Y", bake_space_transform=True, use_mesh_modifiers=False, mesh_smooth_type="FACE",
        use_tspace=True, add_leaf_bones=False, use_armature_deform_only=True, bake_anim=False, path_mode="STRIP",
        embed_textures=False, use_custom_props=False)
    # textures: copy everything this export references; remove obsolete generated files
    keep = set()
    for files in textures.values():
        for f in files:
            src = os.path.join(TEX, f)
            if os.path.exists(src):
                shutil.copyfile(src, os.path.join(DST_TEX, f))
            keep.add(f)
    keep |= set(sk["skins"].values())
    for t in sk["skins"].values():
        shutil.copyfile(os.path.join(TEX, t), os.path.join(DST_TEX, t))
    keep |= {"Hair_wavy_Dye.png"}
    if os.path.exists(os.path.join(TEX, "Giva_Pores_Normal.png")):
        shutil.copyfile(os.path.join(TEX, "Giva_Pores_Normal.png"), os.path.join(DST_TEX, "Giva_Pores_Normal.png"))
        keep.add("Giva_Pores_Normal.png")
    removed = []
    for f in os.listdir(DST_TEX):
        if not f.endswith(".png"):
            continue
        base = f[:-9] + ".png" if f.endswith("_grey.png") else f
        if f in keep or (f.endswith("_grey.png") and base in keep and not f.startswith("Eye_")):
            continue
        for g in (f, f + ".meta"):
            p = os.path.join(DST_TEX, g)
            if os.path.exists(p):
                os.remove(p)
        removed.append(f)
    # desaturated copies (CharacterBuilder.Desaturated writes them only when missing) regenerate from the new sources:
    # every _grey of a texture this export rewrote (a stale Hair_waves_Color_grey.png kept the first hair atlas in game)
    for f in sorted({t[:-4] + "_grey.png" for t in keep if t.endswith(".png") and not t.startswith("Eye_")}):
        for g in (f, f + ".meta"):
            p = os.path.join(DST_TEX, g)
            if os.path.exists(p):
                os.remove(p)
    json.dump(manifest, open(os.path.join(DST, "Lyra.manifest.json"), "w"), indent=1)
    gv.log("EXPORTED", fbx, "meshes", len(man_meshes), "visible tris", manifest["visibleTris"], "correctives", len(corr),
           "removed textures", removed)
    gv.save(os.path.join(gv.OUT, "giva_export.blend"))


main()
