const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
export default async (page, shot, log, base) => {
  await page.goto(base, { waitUntil: 'load' });
  await page.waitForFunction(() => window.__ready === true || window.__bootError, null, { timeout: 180000 });
  await page.evaluate(() => localStorage.removeItem('eoa.appearance'));
  const click = (text) => page.evaluate((t) => { const b = [...document.querySelectorAll('#ui button')].find((x) => x.textContent.trim().toLowerCase().startsWith(t.toLowerCase())); if (b) b.click(); return !!b; }, text);
  log('new game', await click('New Game'));
  await sleep(1500);
  await shot('cs');
  log('customize', await click('Customize'));
  await sleep(1500);
  await shot('dz_presets');
  await click('body'); await sleep(800); await shot('dz_body');
  await click('hair'); await sleep(400);
  await click('Long'); await sleep(1200);
  await shot('dz_hair_long');
  await click('face'); await sleep(1200);
  await shot('dz_face');
  await click('Lyra'); await sleep(800);
  await click('hair'); await sleep(300); await click('Curly'); await sleep(1200);
  await shot('dz_lyra_curly');
  await click('presets'); await sleep(300); await click('Copper'); await sleep(1500);
  await shot('dz_lyra_copper');
  await click('Randomize'); await sleep(1500);
  await shot('dz_random');
  log('stored', await page.evaluate(() => localStorage.getItem('eoa.appearance')?.slice(0, 200)));
  await click('Done'); await sleep(2000);
  await shot('cs_after');
  log('errors', JSON.stringify(await page.evaluate(() => window.__eoa.errors())));
};
