"""Material registry of the street kit (no Blender imports). Same schema as blender/env/matdefs.REGISTRY so envkit
(UV projection, preview colours) and write_manifest share it:

  kind  'baked'  textures generated by st_surfaces.py / st_atlases.py (numpy) or st_interiors.py (Cycles render)
        'param'  parameter-only URP Lit material
  uv    'world' (metres, tiling 1/tile) | 'strip' | 'world0' (authored UVs kept as-is: atlas materials, tile 1)

Only st_* / emit_st_* materials live here; the kit's meshes also use environment-kit materials by name (metal_dark,
glass, emit_neon_*, ...), which EnvLibraryBuilder resolves from Resources/Env/Materials (the environment kit is
built first).
"""
from matdefs_base import lin


def _srgb_to_lin(c):
    return tuple(round(x / 12.92 if x <= 0.04045 else ((x + 0.055) / 1.055) ** 2.4, 4) for x in c)


def B(tile, uv="world", preview=(0.2, 0.2, 0.2), res=1024, unity=None):
    return {"kind": "baked", "tile": tile, "uv": uv, "params": {"color": preview}, "res": res, "unity": unity or {}, "define": None}


def P(base_srgb, smooth, metallic=0.0, emission=None, intensity=0.0, surface="Opaque", **extra):
    u = {"surface": surface, "baseColor": [*base_srgb, extra.pop("alpha", 1.0)], "metallic": metallic, "smoothness": smooth}
    if emission is not None:
        u["emission"] = list(emission)
        u["emissionIntensity"] = intensity
    u.update(extra)
    return {"kind": "param", "unity": u, "preview": _srgb_to_lin(base_srgb if emission is None else emission)}


REGISTRY = {
    # ---- HD street surfaces (st_surfaces.py)
    "st_asphalt": B(6.0, preview=lin("#2c2c2c"), res=2048),
    "st_asphalt_worn": B(6.0, preview=lin("#383838"), res=2048),
    "st_pavers": B(3.6, preview=lin("#6a6a68"), res=2048),
    "st_slab": B(3.6, preview=lin("#707070"), res=1024),
    "st_curb": B(2.0, preview=lin("#5e5a55"), res=1024),
    "st_gutter": B(8.0, uv="strip", preview=lin("#2a2a2a"), res=2048),
    "st_paint_white": B(2.0, preview=lin("#c8c8c8"), res=1024, unity={"alphaClip": 0.5}),
    "st_paint_yellow": B(2.0, preview=lin("#d6a21e"), res=1024, unity={"alphaClip": 0.5}),
    # ---- shop materials (st_atlases.py / st_interiors.py)
    "st_shutter": B(1.0, preview=lin("#6b6f72"), res=1024),
    "st_awning_red": B(1.0, preview=lin("#7a1a1a"), res=1024, unity={"cull": "Off"}),
    "st_awning_teal": B(1.0, preview=lin("#14545a"), res=1024, unity={"cull": "Off"}),
    "st_awning_stripe": B(1.0, preview=lin("#b0a8a0"), res=1024, unity={"cull": "Off"}),
    "st_tile_wall": B(1.2, preview=lin("#8a8f8c"), res=1024),
    "emit_st_signs": B(1.0, uv="world0", preview=lin("#ff4fd8"), res=2048, unity={"emissionIntensity": 3.0}),
    "emit_st_interiors": B(1.0, uv="world0", preview=lin("#ffd8a0"), res=2048, unity={"emissionIntensity": 2.6}),
    # ---- parameter-only
    "st_bag_black": P((0.03, 0.032, 0.035), 0.78),
    "st_bag_blue": P((0.06, 0.16, 0.38), 0.72),
    "st_bag_white": P((0.42, 0.43, 0.41), 0.55),
    "st_paper_wet": P((0.52, 0.5, 0.44), 0.35),
    "st_steel_dark": P((0.07, 0.075, 0.08), 0.55, metallic=0.8),
    "emit_st_lantern_red": P((0.75, 0.12, 0.06), 0.4, emission=(1.0, 0.22, 0.1), intensity=3.2),
    "emit_st_lantern_warm": P((0.85, 0.55, 0.25), 0.4, emission=(1.0, 0.62, 0.3), intensity=3.0),
    "emit_st_led_white": P((0.85, 0.88, 0.9), 0.6, emission=(0.92, 0.96, 1.0), intensity=3.5),
    "emit_st_led_cyan": P((0.1, 0.6, 0.7), 0.6, emission=(0.2, 0.9, 1.0), intensity=4.0),
    "emit_st_led_magenta": P((0.7, 0.1, 0.55), 0.6, emission=(1.0, 0.17, 0.84), intensity=4.0),
    "emit_st_led_amber": P((0.8, 0.5, 0.1), 0.6, emission=(1.0, 0.6, 0.15), intensity=3.5),
}
