"""Write Assets/Art/CityStreet/manifest.json (same schema as the environment kit, read by EnvLibraryBuilder ->
Resources/Env/street_manifest.json) and STREET_ASSETS.md.  Plain python3:  python3 write_manifest.py
"""
import datetime
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import stpaths  # noqa: E402

sys.path.insert(1, stpaths.ENV)
import stmats  # noqa: E402

SURFACES = ["st_asphalt", "st_asphalt_worn", "st_pavers", "st_slab", "st_curb", "st_gutter", "st_paint_white", "st_paint_yellow"]


def lod_hint(size, cat, nlods):
    m = max(size)
    # culled early: beyond ~100-140 m the procedural shopfronts behind the modules carry the street, so the many
    # storefront / wall pieces never pile up into thousands of draws
    if cat == "storefront":
        return [0.25, 0.1, 0.06] if nlods == 3 else [0.22, 0.06]
    if cat in ("wallprop", "overhead"):
        return [0.3, 0.1, 0.04] if nlods == 3 else [0.25, 0.04]
    if m < 1.5:
        return [0.3, 0.1, 0.02] if nlods == 3 else [0.25, 0.03]
    if m < 5:
        return [0.3, 0.1, 0.01] if nlods == 3 else [0.2, 0.015]
    return [0.25, 0.08, 0.004] if nlods == 3 else [0.15, 0.006]


def main():
    baked = json.load(open(os.path.join(stpaths.OUT, "materials_baked.json")))
    assets = json.load(open(os.path.join(stpaths.OUT, "assets.json")))
    dpath = os.path.join(stpaths.OUT, "decals.json")
    decals = json.load(open(dpath)) if os.path.exists(dpath) else {}
    mats = {}
    for name, d in stmats.REGISTRY.items():
        u = dict(d.get("unity", {}))
        if d["kind"] == "param":
            mats[name] = {"kind": "param", "shader": "Universal Render Pipeline/Lit", "surface": u.pop("surface", "Opaque"), **u}
            continue
        b = baked.get(name)
        if not b:
            print("[manifest] WARNING no textures for", name)
            continue
        tile, uv = d["tile"], d["uv"]
        tiling = [round(1 / tile, 6), round(1 / tile, 6)] if uv in ("world", "world0") else [round(1 / tile, 6), 1.0]
        e = {"kind": "baked", "shader": "Universal Render Pipeline/Lit", "surface": u.pop("surface", "Opaque"), "uvMode": uv,
             "tileSizeMeters": tile, "tiling": tiling, "textures": b["textures"], "textureSize": b.get("res", 1024),
             "maxTextureSize": {"desktop": min(2048, b.get("res", 1024)), "webgl": min(1024, b.get("res", 1024))},
             "normalScale": 1.0, "occlusionStrength": 1.0}
        if "Emission" in b["textures"]:
            e["emissionColor"] = [1.0, 1.0, 1.0]
            e["emissionIntensity"] = u.pop("emissionIntensity", 1.0)
        if name in SURFACES:
            e["streetShader"] = "EOA/StreetSurface (CityStreetKit builds it at runtime from this material's maps)"
        e.update(u)
        if "stats" in b:
            e["stats"] = b["stats"]
        mats[name] = e
    recs = sorted(assets.values(), key=lambda r: (r["category"], r["name"]))
    for r in recs:
        r["lodTransitions"] = lod_hint(r["size"], r["category"], len(r["meshes"]))
    tex_bytes = sum(os.path.getsize(os.path.join(root, f)) for root, _, fs in os.walk(stpaths.UNITY_ST) for f in fs if f.endswith(".png"))
    fbx_bytes = sum(os.path.getsize(os.path.join(root, f)) for root, _, fs in os.walk(stpaths.MODELS) for f in fs if f.endswith(".fbx"))
    manifest = {
        "name": "Echoes of Aether - CityStreet kit (street-level storefronts, clutter, overhead signs, HD street surfaces, decals)",
        "generated": datetime.datetime.now().isoformat(timespec="seconds"),
        "generator": "blender/city_street (Blender 5.2 headless + numpy; no AI images). See STREET_ASSETS.md",
        "conventions": {
            "units": "metres; FBX as the environment kit (import at scale 1, identity rotation)",
            "axes": "Unity Y up, asset front +Z. Wall-mounted assets (storefronts, AC, fire escape, hanging signs): pivot at the wall plane, they extend toward +Z.",
            "materials": "Slots named after materials: st_* / emit_st_* are defined here; all other slot names are environment-kit materials.",
            "atlases": "emit_st_signs and emit_st_interiors use authored atlas UVs (uvMode world0, tiling 1).",
        },
        "materials": mats,
        "assets": recs,
        "decals": [decals[k] for k in sorted(decals)],
        "stats": {"assets": len(recs), "materials": len(mats), "decals": len(decals), "textureMB": round(tex_bytes / 1e6, 1), "fbxMB": round(fbx_bytes / 1e6, 1)},
    }
    out = os.path.join(stpaths.UNITY_ST, "manifest.json")
    json.dump(manifest, open(out, "w"), indent=1)
    lines = ["# CityStreet kit (Echoes of Aether)", "",
             f"Generated by `blender/city_street` - {len(recs)} assets, {len(mats)} materials, {len(decals)} decals, textures {manifest['stats']['textureMB']} MB, FBX {manifest['stats']['fbxMB']} MB.",
             "", "Everything is procedural: Blender geometry, numpy textures (FFT noise / periodic Voronoi / SDF glyphs), Cycles renders of modelled",
             "shop interiors. Signs use the kit's invented glyph grammar only (no real words, brands or logos). No AI images, no third-party assets.", "",
             "Rebuild: `python3 st_surfaces.py` (+ `--macro`), `python3 st_atlases.py`, `Blender -b --python st_interiors.py`, `python3 st_decals.py`,",
             "`Blender -b --python st_build.py`, `python3 write_manifest.py`, then EOA > Build Environment Library.", "",
             "## Assets", "", "| Asset | Category | Tris LOD0/LOD1 | Size (m) | Notes |", "|---|---|---|---|---|"]
    for r in recs:
        t = r["tris"]
        lines.append(f"| `{r['name']}` | {r['category']} | {t['LOD0']}/{t['LOD1']} | {r['size']} | {r.get('notes', '')} |")
    lines += ["", "## Materials", "", "| Material | Kind | Tile (m) | Notes |", "|---|---|---|---|"]
    for n, e in mats.items():
        lines.append(f"| `{n}` | {e['kind']} | {e.get('tileSizeMeters', '-')} | {e.get('streetShader', '')} |")
    lines += ["", "## Decals", "", "| Decal | Projection | Size (m) | Use |", "|---|---|---|---|"]
    for k in sorted(decals):
        d = decals[k]
        lines.append(f"| `{k}` | {d['projection']} | {d['sizeMeters']} | {d['use']} |")
    open(os.path.join(stpaths.UNITY_ST, "STREET_ASSETS.md"), "w").write("\n".join(lines) + "\n")
    print(f"[manifest] {len(recs)} assets, {len(mats)} materials, {len(decals)} decals -> {out}")


main()
