"""Write Assets/Art/CityLandmarks/manifest.json (env-kit manifest schema, read by EnvLibraryBuilder -> runtime
Resources/Env/landmarks_manifest.json) and LANDMARKS.md from out/records/*.json and out/kit_materials.json.

  python3 write_manifest.py
"""
import datetime
import json
import os

import lmpaths

CONVENTIONS = {
    "units": "metres; FBX exported with apply_scale_options=FBX_SCALE_ALL, bake_space_transform=True, axis_forward=-Z, axis_up=Y -> import at scale 1, identity rotation",
    "axes": "Unity Y up, asset FRONT = +Z (Blender -Y). Prototype mapping: Unity = (-x, y, z); a yaw of 0 faces prototype +z (south).",
    "pivot": "base-centre of the building MASS for landmarks / buildings / plaza blocks; roof sets: base-centre on the roof slab; "
             "facade pieces ('wall-base'): centre of the bottom edge on the host wall plane, projecting toward +Z",
    "lods": "<Name>_LOD0/1/2 siblings -> LODGroup. LOD1 ~25-40% (openings with reveals, big props), LOD2 ~3-6% (flat walls + flush lit "
            "window panes so the night silhouette survives). lodTransitions: one value per LOD, last = cull (0 = never, the city culler handles it).",
    "materials": "Max 8 slots per asset: env-kit tiling materials + this kit's lm_* materials + the shared building atlases "
                 "(building_trim_atlas, emit_building_atlas; defined in the Environment manifest) + env holo/glass.",
    "uv0": "metres for tiling materials (world-scale, explicit facade UVs: U along the wall, V = height); atlas faces use 0..1 atlas UVs.",
    "colliders": "box colliders in Unity local space (centre/size). Landmarks carry their own colliders; plaza blocks / kit buildings: the "
                 "zone code keeps its mass collider, the manifest box is the mass.",
    "textures": "BaseColor sRGB, Normal OpenGL (Unity convention), MaskMap linear RGBA (R metallic, G AO, B height, A smoothness); "
                "Occlusion points at the MaskMap (URP samples .g).",
}


def lod_hint(cat, size):
    if cat == "landmark":
        return [0.3, 0.1, 0.0]
    if cat in ("building", "plaza"):
        return [0.22, 0.07, 0.0]
    m = max(size)
    return [0.3, 0.1, 0.012] if m < 12 else [0.25, 0.08, 0.006]


def main():
    recs = []
    for f in sorted(os.listdir(lmpaths.RECORDS)):
        if f.endswith(".json"):
            r = json.load(open(os.path.join(lmpaths.RECORDS, f)))
            if os.path.exists(os.path.join(lmpaths.KIT, r["file"])):
                recs.append(r)
    order = {"landmark": 0, "building": 1, "plaza": 2, "module": 3}
    recs.sort(key=lambda r: (order.get(r["category"], 9), r.get("district", ""), r["name"]))
    for r in recs:
        r["lodTransitions"] = lod_hint(r["category"], r["size"])
        if r.get("colliders") == "none":
            r["colliders"] = []
    mats = json.load(open(os.path.join(lmpaths.OUT, "kit_materials.json")))
    tex_bytes = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(lmpaths.TEXTURES) for f in fs if f.endswith(".png"))
    fbx_bytes = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(lmpaths.MODELS) for f in fs if f.endswith(".fbx"))
    man = {
        "name": "Echoes of Aether - city landmarks & district buildings kit",
        "generated": datetime.datetime.now().isoformat(timespec="seconds"),
        "generator": "blender/city_landmarks (Blender 5.2 headless + numpy, fully procedural). Rebuild: see LANDMARKS.md",
        "conventions": CONVENTIONS,
        "materials": mats,
        "assets": recs,
        "stats": {"assets": len(recs), "materials": len(mats), "textureMB": round(tex_bytes / 1e6, 1), "fbxMB": round(fbx_bytes / 1e6, 1),
                  "trisLOD0": sum(r["tris"]["LOD0"] for r in recs)},
    }
    p = os.path.join(lmpaths.KIT, "manifest.json")
    json.dump(man, open(p + ".tmp", "w"), indent=1)
    os.replace(p + ".tmp", p)
    # markdown catalogue
    lines = ["# City landmarks & district buildings kit (Echoes of Aether)", "",
             "Generated by `blender/city_landmarks` (Blender 5.2 headless + numpy; everything procedural, no AI images, no photos). "
             "Source of truth: `manifest.json` next to this file.", "",
             f"{len(recs)} assets, {len(mats)} kit materials, textures {man['stats']['textureMB']} MB, FBX {man['stats']['fbxMB']} MB.", "",
             "## Rebuild", "", "```",
             "cd blender/city_landmarks",
             "python3 lmmats.py                      # lm_* tiling materials (2K, macro-varied)",
             "python3 atlas_build.py --preview        # building_trim_atlas + emit_building_atlas (env kit textures)",
             "Blender -b --factory-startup --python rebuild_env_buildings.py && python3 patch_env_manifest.py   # env Building_* -> <= 8 mats",
             "Blender -b --factory-startup --python build.py -- [names/globs]   # landmarks, district buildings, plaza blocks, modules",
             "python3 write_manifest.py",
             "Blender -b --factory-startup --python render_lm.py -- previews/sheet.png 'LM_*'   # Cycles previews",
             "```", "", "## Conventions", ""]
    for k, v in CONVENTIONS.items():
        lines.append(f"- **{k}**: {v}")
    lines += ["", "## Materials", "", "| Material | Tile (m) | Size | Notes |", "|---|---|---|---|"]
    for k, v in mats.items():
        lines.append(f"| `{k}` | {v['tileSizeMeters']} | {v['textureSize']} | albedo {v['stats']['albedo_mean_srgb']} |")
    lines += ["", "Shared atlases (Environment kit): `building_trim_atlas` (trim bands that tile along U + flat colour cells) and "
              "`emit_building_atlas` (LED ads, light boxes, 14 residential window interiors, 16 office panes, 9 lightbox signs, LED strips, "
              "neon / lamp colours). Window interiors vary per floor (each floor has its own activity; LOD0/1/2 pick the same cells).", ""]
    for cat in ("landmark", "building", "plaza", "module"):
        rs = [r for r in recs if r["category"] == cat]
        if not rs:
            continue
        lines += [f"## {cat.title()}s", "", "| Asset | District | Size (m) | Tris LOD0/1/2 | Mats | Notes |", "|---|---|---|---|---|---|"]
        for r in rs:
            t = r["tris"]
            lines.append(f"| `{r['name']}` | {r.get('district', '')} | {' x '.join(f'{x:.1f}' for x in r['size'])} | "
                         f"{t['LOD0']} / {t['LOD1']} / {t.get('LOD2', 0)} | {len(r['materials'])} | {r.get('notes', '')} |")
        lines.append("")
    open(os.path.join(lmpaths.KIT, "LANDMARKS.md"), "w").write("\n".join(lines) + "\n")
    print(f"[manifest] {len(recs)} assets, {len(mats)} materials -> {p}")


if __name__ == "__main__":
    main()
