#!/usr/bin/env python3
"""Writes the voice-over recording script for Echoes of Aether from the game's dialogue data.

Outputs:
  docs/VO_SCRIPT.md     - per character: every line, its context and the exact file name to record
  tools/vo/vo_lines.csv - the same as a spreadsheet (one row per recording)

Recordings go to unity/EchoesOfAether/Assets/Resources/Audio/Voice/<dialogue id>/<file>.wav (or .ogg):
mono, 48 kHz, 24-bit WAV, peaks around -3 dBFS, ~0.2 s of room tone before and after, no music or effects.
Lines whose speaker is the player's hero or partner need two takes: <node>_kael and <node>_lyra.
Only real human recordings belong here: the game never synthesises speech.
"""
import csv
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA = os.path.join(ROOT, "unity", "EchoesOfAether", "Assets", "Resources", "Data")
SKIP = {"system"}  # UI/system messages stay text-only

dialogues = json.load(open(os.path.join(DATA, "dialogue.json"), encoding="utf-8"))["dialogues"]
speakers = json.load(open(os.path.join(DATA, "speakers.json"), encoding="utf-8"))
speakers = speakers.get("speakers", speakers)
if isinstance(speakers, list):
    speakers = {s["id"]: s for s in speakers}


def name(sid):
    return speakers.get(sid, {}).get("name", sid)


rows = []
for d in dialogues:
    for n in d["nodes"]:
        text, sp = n.get("text"), n.get("speaker")
        if not text or not sp or sp in SKIP:
            continue
        kind = "cinematic" if d.get("cinematic") else ("radio" if d.get("radio") else "conversation")
        if sp in ("active", "partner"):
            for hero, partner in (("kael", "lyra"), ("lyra", "kael")):
                who = hero if sp == "active" else partner
                t = text.replace("{active}", name(hero).split()[0]).replace("{partner}", name(partner).split()[0])
                rows.append((who, d["id"], n["id"], f"{n['id']}_{who}", t, kind, f"player is {name(hero).split()[0]}"))
        else:
            t = text.replace("{active}", "<hero name>").replace("{partner}", "<partner name>")
            rows.append((sp, d["id"], n["id"], n["id"], t, kind, ""))

os.makedirs(os.path.join(ROOT, "docs"), exist_ok=True)
with open(os.path.join(ROOT, "tools", "vo", "vo_lines.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["speaker", "speaker_name", "dialogue", "node", "file", "text", "context", "note"])
    for sp, dlg, node, file, text, kind, note in rows:
        w.writerow([sp, name(sp), dlg, node, f"Audio/Voice/{dlg}/{file}.wav", text, kind, note])

by_speaker = {}
for r in rows:
    by_speaker.setdefault(r[0], []).append(r)
lines = [
    "# Echoes of Aether — voice-over recording script",
    "",
    "Generated by `python3 tools/vo/make_vo_script.py` from the game's dialogue data. Re-run it after dialogue changes.",
    "",
    "The game never synthesises speech: a line plays a voice only when a **human recording** exists. Lines without",
    "a recording stay subtitle-only, so recordings can be added a character at a time.",
    "",
    "**Delivery:** mono WAV, 48 kHz, 24-bit, peaks around -3 dBFS, ~0.2 s room tone at both ends, dry (no music/effects).",
    "**Location:** `unity/EchoesOfAether/Assets/Resources/Audio/Voice/<dialogue>/<file>.wav` (the file names below).",
    "Lines spoken by the player's hero or partner need one take per hero (`_kael` / `_lyra`).",
    "",
    f"Total recordings: **{len(rows)}** across {len(by_speaker)} speakers.",
    "",
]
for sp in sorted(by_speaker, key=lambda s: -len(by_speaker[s])):
    rs = by_speaker[sp]
    lines += [f"## {name(sp)} ({sp}) — {len(rs)} lines", "", "| File | Line | Context |", "|---|---|---|"]
    for _, dlg, node, file, text, kind, note in rs:
        ctx = kind + (f", {note}" if note else "")
        lines.append(f"| `{dlg}/{file}` | {text.replace('|', '/')} | {ctx} |")
    lines.append("")
open(os.path.join(ROOT, "docs", "VO_SCRIPT.md"), "w", encoding="utf-8").write("\n".join(lines))
print(f"{len(rows)} recordings for {len(by_speaker)} speakers -> docs/VO_SCRIPT.md, tools/vo/vo_lines.csv")
